# Generated by Django 2.0.5 on 2018-05-24 21:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('init_date', models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 5, 24, 21, 12, 52, 825201, tzinfo=utc))),
                ('image', models.CharField(default='default_basemap_image.jpg', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(default='default_client_image.jpg', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HeroGeometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_name', models.CharField(max_length=200)),
                ('init_date', models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 5, 24, 21, 12, 52, 832198, tzinfo=utc))),
                ('image', models.CharField(default='default_herogeometry_image.jpg', max_length=200)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drafter.Client')),
            ],
        ),
        migrations.CreateModel(
            name='InstanceMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.CharField(default='default_instancemap_image.jpg', max_length=200)),
                ('basemap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='drafter.BaseMap')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drafter.Client')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('init_date', models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 5, 24, 21, 12, 52, 824201, tzinfo=utc))),
                ('image', models.CharField(default='default_project_image.jpg', max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drafter.Client')),
            ],
        ),
        migrations.AddField(
            model_name='instancemap',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drafter.Project'),
        ),
        migrations.AddField(
            model_name='herogeometry',
            name='instancemaps',
            field=models.ManyToManyField(to='drafter.InstanceMap'),
        ),
    ]
