# Generated by Django 2.0.5 on 2018-06-22 09:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0002_auto_20180618_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemap',
            name='init_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 6, 22, 9, 38, 47, 523967, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='herogeometry',
            name='init_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 6, 22, 9, 38, 47, 524969, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='instancemap',
            name='init_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 6, 22, 9, 38, 47, 523967, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='init_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 6, 22, 9, 38, 47, 523967, tzinfo=utc)),
        ),
    ]
