# Generated by Django 2.0.5 on 2018-06-16 20:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0003_auto_20180616_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemap',
            name='init_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 6, 16, 20, 24, 14, 899767, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='herogeometry',
            name='init_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 6, 16, 20, 24, 14, 900766, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='instancemap',
            name='init_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 6, 16, 20, 24, 14, 899767, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='init_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 6, 16, 20, 24, 14, 898767, tzinfo=utc)),
        ),
    ]
