# Generated by Django 2.0.6 on 2018-06-28 09:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0003_auto_20180622_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemap',
            name='init_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 6, 28, 9, 30, 18, 519805, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='herogeometry',
            name='init_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 6, 28, 9, 30, 18, 520807, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='instancemap',
            name='init_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 6, 28, 9, 30, 18, 519805, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='init_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 6, 28, 9, 30, 18, 519805, tzinfo=utc)),
        ),
    ]
