# Generated by Django 2.0.7 on 2018-07-12 08:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0004_auto_20180628_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemap',
            name='init_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 7, 12, 8, 54, 57, 546932, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='herogeometry',
            name='init_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 7, 12, 8, 54, 57, 546932, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='instancemap',
            name='init_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 7, 12, 8, 54, 57, 546932, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='init_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 7, 12, 8, 54, 57, 546932, tzinfo=utc)),
        ),
    ]
