# Generated by Django 2.0.7 on 2018-11-27 19:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0005_auto_20180712_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemap',
            name='init_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 11, 27, 19, 29, 47, 843601, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='herogeometry',
            name='init_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 11, 27, 19, 29, 47, 843601, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='instancemap',
            name='init_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 11, 27, 19, 29, 47, 843601, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='init_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 11, 27, 19, 29, 47, 843601, tzinfo=utc)),
        ),
    ]
