# Generated by Django 2.0.5 on 2018-05-26 15:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='client',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.AddField(
            model_name='basemap',
            name='image_thumb',
            field=models.CharField(default='default_basemap_image_thumb.jpg', max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='image_thumb',
            field=models.CharField(default='default_client_image_thumb.jpg', max_length=200),
        ),
        migrations.AddField(
            model_name='herogeometry',
            name='image_thumb',
            field=models.CharField(default='default_herogeometry_image_thumb.jpg', max_length=200),
        ),
        migrations.AddField(
            model_name='instancemap',
            name='image_thumb',
            field=models.CharField(default='default_instancemap_image_thumb.jpg', max_length=200),
        ),
        migrations.AddField(
            model_name='instancemap',
            name='init_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 5, 26, 15, 53, 14, 924381, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='project',
            name='image_thumb',
            field=models.CharField(default='default_project_image_thumb.jpg', max_length=200),
        ),
        migrations.AlterField(
            model_name='basemap',
            name='init_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 5, 26, 15, 53, 14, 923384, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='herogeometry',
            name='init_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 5, 26, 15, 53, 14, 924381, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='init_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 5, 26, 15, 53, 14, 923384, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
