# Generated by Django 2.0.5 on 2018-05-23 16:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('drafter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='basemap',
            name='init_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 5, 23, 16, 20, 38, 612475, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='herogeometry',
            name='init_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 5, 23, 16, 20, 38, 611477, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='project',
            name='init_date',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2018, 5, 23, 16, 20, 38, 611477, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='basemap',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
